apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: 100ms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 100ms.rudub.com
    http:
      paths:
      - backend:
          serviceName: hundred-ms
          servicePort: 5000
        path: /
